# Generated by Django 4.2.4 on 2023-09-13 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
