# Generated by Django 4.2.4 on 2023-09-13 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0002_alter_vendor_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_size', models.CharField(blank=True, max_length=255, null=True)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_sku', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sams.vendor')),
            ],
        ),
    ]
